# Generated by dump_input.py, do not edit
{
  description = "Neovim with plugins";
  inputs = {
    neovim = {
      url = "github:neovim/neovim";
      flake = false;
    };

    lazyDOTnvim = {
      url = "github:folke/lazy.nvim";
      flake = false;
    };
    plenaryDOTnvim = {
      url = "github:nvim-lua/plenary.nvim";
      flake = false;
    };
    telescope-fzf-nativeDOTnvim = {
      url = "github:nvim-telescope/telescope-fzf-native.nvim";
      flake = false;
    };
    telescope-vim-bookmarksDOTnvim = {
      url = "github:tom-anders/telescope-vim-bookmarks.nvim";
      flake = false;
    };
    telescopeDOTnvim = {
      url = "github:nvim-telescope/telescope.nvim";
      flake = false;
    };
    sigsegvim = {
      url = "github:seandewar/sigsegvim";
      flake = false;
    };
    cellular-automatonDOTnvim = {
      url = "github:Eandrju/cellular-automaton.nvim";
      flake = false;
    };
    telescope-live-grep-argsDOTnvim = {
      url = "github:nvim-telescope/telescope-live-grep-args.nvim";
      flake = false;
    };
    nvim-bqf = {
      url = "github:kevinhwang91/nvim-bqf";
      flake = false;
    };
    nvim-hlslens = {
      url = "github:kevinhwang91/nvim-hlslens";
      flake = false;
    };
    masonDOTnvim = {
      url = "github:williamboman/mason.nvim";
      flake = false;
    };
    nvim-jdtls = {
      url = "github:mfussenegger/nvim-jdtls";
      flake = false;
    };
    rust-toolsDOTnvim = {
      url = "github:simrat39/rust-tools.nvim";
      flake = false;
    };
    clangd_extensionsDOTnvim = {
      url = "github:p00f/clangd_extensions.nvim";
      flake = false;
    };
    nvim-lspconfig = {
      url = "github:neovim/nvim-lspconfig";
      flake = false;
    };
    statuscolDOTnvim = {
      url = "github:luukvbaal/statuscol.nvim?ref=0.10";
      flake = false;
    };
    nvim-lightbulb = {
      url = "github:kosayoda/nvim-lightbulb";
      flake = false;
    };
    fidgetDOTnvim = {
      url = "github:j-hui/fidget.nvim?ref=legacy";
      flake = false;
    };
    nvim-web-devicons = {
      url = "github:kyazdani42/nvim-web-devicons";
      flake = false;
    };
    nvim-autopairs = {
      url = "github:windwp/nvim-autopairs";
      flake = false;
    };
    auto-saveDOTnvim = {
      url = "github:Pocco81/auto-save.nvim";
      flake = false;
    };
    none-lsDOTnvim = {
      url = "github:nvimtools/none-ls.nvim";
      flake = false;
    };
    ultisnips = {
      url = "github:SirVer/ultisnips";
      flake = false;
    };
    cmp-nvim-ultisnips = {
      url = "github:quangnguyen30192/cmp-nvim-ultisnips";
      flake = false;
    };
    vim-vsnip = {
      url = "github:hrsh7th/vim-vsnip";
      flake = false;
    };
    cmp-nvim-lsp = {
      url = "github:hrsh7th/cmp-nvim-lsp";
      flake = false;
    };
    cmp-nvim-lua = {
      url = "github:hrsh7th/cmp-nvim-lua";
      flake = false;
    };
    cmp-path = {
      url = "github:hrsh7th/cmp-path";
      flake = false;
    };
    cmp-buffer = {
      url = "github:hrsh7th/cmp-buffer";
      flake = false;
    };
    cmp-omni = {
      url = "github:hrsh7th/cmp-omni";
      flake = false;
    };
    cmp-nvim-lsp-signature-help = {
      url = "github:hrsh7th/cmp-nvim-lsp-signature-help";
      flake = false;
    };
    cmp-dictionary = {
      url = "github:uga-rosa/cmp-dictionary";
      flake = false;
    };
    cmp-dap = {
      url = "github:rcarriga/cmp-dap";
      flake = false;
    };
    cmp-cmdline = {
      url = "github:hrsh7th/cmp-cmdline";
      flake = false;
    };
    lsp_signatureDOTnvim = {
      url = "github:ray-x/lsp_signature.nvim";
      flake = false;
    };
    nvim-cmp = {
      url = "github:hrsh7th/nvim-cmp";
      flake = false;
    };
    promise-async = {
      url = "github:kevinhwang91/promise-async";
      flake = false;
    };
    nvim-fundo = {
      url = "github:kevinhwang91/nvim-fundo";
      flake = false;
    };
    nvim-ufo = {
      url = "github:kevinhwang91/nvim-ufo?rev=ebbab711d909d5f675e38ad489765bd22bd2c6b3";
      flake = false;
    };
    toggletermDOTnvim = {
      url = "github:akinsho/toggleterm.nvim";
      flake = false;
    };
    nvim-treesitter = {
      url = "github:nvim-treesitter/nvim-treesitter";
      flake = false;
    };
    playground = {
      url = "github:nvim-treesitter/playground";
      flake = false;
    };
    nvim-treesitter-textobjects = {
      url = "github:nvim-treesitter/nvim-treesitter-textobjects";
      flake = false;
    };
    indent-blanklineDOTnvim = {
      url = "github:lukas-reineke/indent-blankline.nvim";
      flake = false;
    };
    rainbow-delimitersDOTnvim = {
      url = "github:HiPhish/rainbow-delimiters.nvim";
      flake = false;
    };
    nvim-ts-autotag = {
      url = "github:windwp/nvim-ts-autotag";
      flake = false;
    };
    nvim-treesitter-context = {
      url = "github:nvim-treesitter/nvim-treesitter-context";
      flake = false;
    };
    hlargsDOTnvim = {
      url = "github:m-demare/hlargs.nvim";
      flake = false;
    };
    projectDOTnvim = {
      url = "github:ahmedkhalf/project.nvim";
      flake = false;
    };
    aerialDOTnvim = {
      url = "github:stevearc/aerial.nvim";
      flake = false;
    };
    dropbarDOTnvim = {
      url = "github:Bekaboo/dropbar.nvim";
      flake = false;
    };
    gitsignsDOTnvim = {
      url = "github:lewis6991/gitsigns.nvim";
      flake = false;
    };
    git-conflictDOTnvim = {
      url = "github:akinsho/git-conflict.nvim";
      flake = false;
    };
    diffviewDOTnvim = {
      url = "github:sindrets/diffview.nvim";
      flake = false;
    };
    nvim-colorizerDOTlua = {
      url = "github:NvChad/nvim-colorizer.lua";
      flake = false;
    };
    bufferlineDOTnvim = {
      url = "github:akinsho/bufferline.nvim";
      flake = false;
    };
    alignDOTnvim = {
      url = "github:Vonr/align.nvim";
      flake = false;
    };
    dialDOTnvim = {
      url = "github:monaqa/dial.nvim";
      flake = false;
    };
    dressingDOTnvim = {
      url = "github:stevearc/dressing.nvim";
      flake = false;
    };
    inc-renameDOTnvim = {
      url = "github:smjonas/inc-rename.nvim";
      flake = false;
    };
    lualineDOTnvim = {
      url = "github:nvim-lualine/lualine.nvim";
      flake = false;
    };
    rnvimr = {
      url = "github:kevinhwang91/rnvimr";
      flake = false;
    };
    vim-illuminate = {
      url = "github:RRethy/vim-illuminate";
      flake = false;
    };
    nvim-treeDOTlua = {
      url = "github:kyazdani42/nvim-tree.lua";
      flake = false;
    };
    bufdeleteDOTnvim = {
      url = "github:famiu/bufdelete.nvim";
      flake = false;
    };
    vim-bookmarks = {
      url = "github:MattesGroeger/vim-bookmarks";
      flake = false;
    };
    auto-session = {
      url = "github:rmagatti/auto-session";
      flake = false;
    };
    alpha-nvim = {
      url = "github:goolord/alpha-nvim";
      flake = false;
    };
    registersDOTnvim = {
      url = "github:tversteeg/registers.nvim";
      flake = false;
    };
    CommentDOTnvim = {
      url = "github:numToStr/Comment.nvim";
      flake = false;
    };
    troubleDOTnvim = {
      url = "github:folke/trouble.nvim";
      flake = false;
    };
    hopDOTnvim = {
      url = "github:smoka7/hop.nvim";
      flake = false;
    };
    flashDOTnvim = {
      url = "github:folke/flash.nvim";
      flake = false;
    };
    which-keyDOTnvim = {
      url = "github:folke/which-key.nvim";
      flake = false;
    };
    satelliteDOTnvim = {
      url = "github:lewis6991/satellite.nvim";
      flake = false;
    };
    todo-commentsDOTnvim = {
      url = "github:folke/todo-comments.nvim";
      flake = false;
    };
    nvim-notify = {
      url = "github:rcarriga/nvim-notify";
      flake = false;
    };
    lsp_linesDOTnvim = {
      url = "git+https://git.sr.ht/~whynothugo/lsp_lines.nvim";
      flake = false;
    };
    nvim-osc52 = {
      url = "github:ojroques/nvim-osc52";
      flake = false;
    };
    copilotDOTvim = {
      url = "github:github/copilot.vim";
      flake = false;
    };
    firenvim = {
      url = "github:glacambre/firenvim";
      flake = false;
    };
    nvim-dap-python = {
      url = "github:mfussenegger/nvim-dap-python";
      flake = false;
    };
    venv-selectorDOTnvim = {
      url = "github:linux-cultist/venv-selector.nvim";
      flake = false;
    };
    vim-matchup = {
      url = "github:andymass/vim-matchup";
      flake = false;
    };
    vim-sleuth = {
      url = "github:tpope/vim-sleuth";
      flake = false;
    };
    pantranDOTnvim = {
      url = "github:potamides/pantran.nvim";
      flake = false;
    };
    rainbow = {
      url = "github:luochen1990/rainbow";
      flake = false;
    };
    markdown-previewDOTnvim = {
      url = "github:iamcco/markdown-preview.nvim";
      flake = false;
    };
    vim-textobj-user = {
      url = "github:kana/vim-textobj-user";
      flake = false;
    };
    vim-textobj-entire = {
      url = "github:kana/vim-textobj-entire";
      flake = false;
    };
    vim-interestingwords = {
      url = "github:lfv89/vim-interestingwords";
      flake = false;
    };
    vim-skeletons = {
      url = "github:qsdrqs/vim-skeletons";
      flake = false;
    };
    vim-snippets = {
      url = "github:honza/vim-snippets";
      flake = false;
    };
    sudaDOTvim = {
      url = "github:lambdalisue/suda.vim";
      flake = false;
    };
    undotree = {
      url = "github:mbbill/undotree";
      flake = false;
    };
    vim-sandwich = {
      url = "github:machakann/vim-sandwich";
      flake = false;
    };
    vim-log-highlighting = {
      url = "github:MTDL9/vim-log-highlighting";
      flake = false;
    };
    telescope-asynctasksDOTnvim = {
      url = "github:GustavoKatel/telescope-asynctasks.nvim";
      flake = false;
    };
    asyncrunDOTvim = {
      url = "github:skywind3000/asyncrun.vim";
      flake = false;
    };
    asynctasksDOTvim = {
      url = "github:skywind3000/asynctasks.vim";
      flake = false;
    };
    vCoolorDOTvim = {
      url = "github:KabbAmine/vCoolor.vim";
      flake = false;
    };
    vim-fugitive = {
      url = "github:tpope/vim-fugitive";
      flake = false;
    };
    vim-flog = {
      url = "github:rbong/vim-flog";
      flake = false;
    };
    vim-visual-multi = {
      url = "github:mg979/vim-visual-multi";
      flake = false;
    };
    cscope_mapsDOTnvim = {
      url = "github:dhananjaylatkar/cscope_maps.nvim";
      flake = false;
    };
    vim-gutentags = {
      url = "github:skywind3000/vim-gutentags";
      flake = false;
    };
    gutentags_plus = {
      url = "github:skywind3000/gutentags_plus";
      flake = false;
    };
    nvim-dap-ui = {
      url = "github:rcarriga/nvim-dap-ui";
      flake = false;
    };
    nvim-dap-virtual-text = {
      url = "github:theHamsta/nvim-dap-virtual-text";
      flake = false;
    };
    nvim-dap = {
      url = "github:mfussenegger/nvim-dap";
      flake = false;
    };
  };
  outputs = { self, ... }@inputs:
    {
      plugins_list = [
        { name = "lazy.nvim"; dotname = "lazyDOTnvim";source = inputs.lazyDOTnvim; build = false; }
        { name = "plenary.nvim"; dotname = "plenaryDOTnvim";source = inputs.plenaryDOTnvim; build = false; }
        { name = "telescope-fzf-native.nvim"; dotname = "telescope-fzf-nativeDOTnvim";source = inputs.telescope-fzf-nativeDOTnvim; build = true; }
        { name = "telescope-vim-bookmarks.nvim"; dotname = "telescope-vim-bookmarksDOTnvim";source = inputs.telescope-vim-bookmarksDOTnvim; build = false; }
        { name = "telescope.nvim"; dotname = "telescopeDOTnvim";source = inputs.telescopeDOTnvim; build = false; }
        { name = "sigsegvim"; dotname = "sigsegvim";source = inputs.sigsegvim; build = false; }
        { name = "cellular-automaton.nvim"; dotname = "cellular-automatonDOTnvim";source = inputs.cellular-automatonDOTnvim; build = false; }
        { name = "telescope-live-grep-args.nvim"; dotname = "telescope-live-grep-argsDOTnvim";source = inputs.telescope-live-grep-argsDOTnvim; build = false; }
        { name = "nvim-bqf"; dotname = "nvim-bqf";source = inputs.nvim-bqf; build = false; }
        { name = "nvim-hlslens"; dotname = "nvim-hlslens";source = inputs.nvim-hlslens; build = false; }
        { name = "mason.nvim"; dotname = "masonDOTnvim";source = inputs.masonDOTnvim; build = false; }
        { name = "nvim-jdtls"; dotname = "nvim-jdtls";source = inputs.nvim-jdtls; build = false; }
        { name = "rust-tools.nvim"; dotname = "rust-toolsDOTnvim";source = inputs.rust-toolsDOTnvim; build = false; }
        { name = "clangd_extensions.nvim"; dotname = "clangd_extensionsDOTnvim";source = inputs.clangd_extensionsDOTnvim; build = false; }
        { name = "nvim-lspconfig"; dotname = "nvim-lspconfig";source = inputs.nvim-lspconfig; build = false; }
        { name = "statuscol.nvim"; dotname = "statuscolDOTnvim";source = inputs.statuscolDOTnvim; build = false; }
        { name = "nvim-lightbulb"; dotname = "nvim-lightbulb";source = inputs.nvim-lightbulb; build = false; }
        { name = "fidget.nvim"; dotname = "fidgetDOTnvim";source = inputs.fidgetDOTnvim; build = false; }
        { name = "nvim-web-devicons"; dotname = "nvim-web-devicons";source = inputs.nvim-web-devicons; build = false; }
        { name = "nvim-autopairs"; dotname = "nvim-autopairs";source = inputs.nvim-autopairs; build = false; }
        { name = "auto-save.nvim"; dotname = "auto-saveDOTnvim";source = inputs.auto-saveDOTnvim; build = false; }
        { name = "none-ls.nvim"; dotname = "none-lsDOTnvim";source = inputs.none-lsDOTnvim; build = false; }
        { name = "ultisnips"; dotname = "ultisnips";source = inputs.ultisnips; build = false; }
        { name = "cmp-nvim-ultisnips"; dotname = "cmp-nvim-ultisnips";source = inputs.cmp-nvim-ultisnips; build = false; }
        { name = "vim-vsnip"; dotname = "vim-vsnip";source = inputs.vim-vsnip; build = false; }
        { name = "cmp-nvim-lsp"; dotname = "cmp-nvim-lsp";source = inputs.cmp-nvim-lsp; build = false; }
        { name = "cmp-nvim-lua"; dotname = "cmp-nvim-lua";source = inputs.cmp-nvim-lua; build = false; }
        { name = "cmp-path"; dotname = "cmp-path";source = inputs.cmp-path; build = false; }
        { name = "cmp-buffer"; dotname = "cmp-buffer";source = inputs.cmp-buffer; build = false; }
        { name = "cmp-omni"; dotname = "cmp-omni";source = inputs.cmp-omni; build = false; }
        { name = "cmp-nvim-lsp-signature-help"; dotname = "cmp-nvim-lsp-signature-help";source = inputs.cmp-nvim-lsp-signature-help; build = false; }
        { name = "cmp-dictionary"; dotname = "cmp-dictionary";source = inputs.cmp-dictionary; build = false; }
        { name = "cmp-dap"; dotname = "cmp-dap";source = inputs.cmp-dap; build = false; }
        { name = "cmp-cmdline"; dotname = "cmp-cmdline";source = inputs.cmp-cmdline; build = false; }
        { name = "lsp_signature.nvim"; dotname = "lsp_signatureDOTnvim";source = inputs.lsp_signatureDOTnvim; build = false; }
        { name = "nvim-cmp"; dotname = "nvim-cmp";source = inputs.nvim-cmp; build = false; }
        { name = "promise-async"; dotname = "promise-async";source = inputs.promise-async; build = false; }
        { name = "nvim-fundo"; dotname = "nvim-fundo";source = inputs.nvim-fundo; build = true; }
        { name = "nvim-ufo"; dotname = "nvim-ufo";source = inputs.nvim-ufo; build = false; }
        { name = "toggleterm.nvim"; dotname = "toggletermDOTnvim";source = inputs.toggletermDOTnvim; build = false; }
        { name = "nvim-treesitter"; dotname = "nvim-treesitter";source = inputs.nvim-treesitter; build = true; }
        { name = "playground"; dotname = "playground";source = inputs.playground; build = false; }
        { name = "nvim-treesitter-textobjects"; dotname = "nvim-treesitter-textobjects";source = inputs.nvim-treesitter-textobjects; build = false; }
        { name = "indent-blankline.nvim"; dotname = "indent-blanklineDOTnvim";source = inputs.indent-blanklineDOTnvim; build = false; }
        { name = "rainbow-delimiters.nvim"; dotname = "rainbow-delimitersDOTnvim";source = inputs.rainbow-delimitersDOTnvim; build = false; }
        { name = "nvim-ts-autotag"; dotname = "nvim-ts-autotag";source = inputs.nvim-ts-autotag; build = false; }
        { name = "nvim-treesitter-context"; dotname = "nvim-treesitter-context";source = inputs.nvim-treesitter-context; build = false; }
        { name = "hlargs.nvim"; dotname = "hlargsDOTnvim";source = inputs.hlargsDOTnvim; build = false; }
        { name = "project.nvim"; dotname = "projectDOTnvim";source = inputs.projectDOTnvim; build = false; }
        { name = "aerial.nvim"; dotname = "aerialDOTnvim";source = inputs.aerialDOTnvim; build = false; }
        { name = "dropbar.nvim"; dotname = "dropbarDOTnvim";source = inputs.dropbarDOTnvim; build = false; }
        { name = "gitsigns.nvim"; dotname = "gitsignsDOTnvim";source = inputs.gitsignsDOTnvim; build = false; }
        { name = "git-conflict.nvim"; dotname = "git-conflictDOTnvim";source = inputs.git-conflictDOTnvim; build = false; }
        { name = "diffview.nvim"; dotname = "diffviewDOTnvim";source = inputs.diffviewDOTnvim; build = false; }
        { name = "nvim-colorizer.lua"; dotname = "nvim-colorizerDOTlua";source = inputs.nvim-colorizerDOTlua; build = false; }
        { name = "bufferline.nvim"; dotname = "bufferlineDOTnvim";source = inputs.bufferlineDOTnvim; build = false; }
        { name = "align.nvim"; dotname = "alignDOTnvim";source = inputs.alignDOTnvim; build = false; }
        { name = "dial.nvim"; dotname = "dialDOTnvim";source = inputs.dialDOTnvim; build = false; }
        { name = "dressing.nvim"; dotname = "dressingDOTnvim";source = inputs.dressingDOTnvim; build = false; }
        { name = "inc-rename.nvim"; dotname = "inc-renameDOTnvim";source = inputs.inc-renameDOTnvim; build = false; }
        { name = "lualine.nvim"; dotname = "lualineDOTnvim";source = inputs.lualineDOTnvim; build = false; }
        { name = "rnvimr"; dotname = "rnvimr";source = inputs.rnvimr; build = false; }
        { name = "vim-illuminate"; dotname = "vim-illuminate";source = inputs.vim-illuminate; build = false; }
        { name = "nvim-tree.lua"; dotname = "nvim-treeDOTlua";source = inputs.nvim-treeDOTlua; build = false; }
        { name = "bufdelete.nvim"; dotname = "bufdeleteDOTnvim";source = inputs.bufdeleteDOTnvim; build = false; }
        { name = "vim-bookmarks"; dotname = "vim-bookmarks";source = inputs.vim-bookmarks; build = false; }
        { name = "auto-session"; dotname = "auto-session";source = inputs.auto-session; build = false; }
        { name = "alpha-nvim"; dotname = "alpha-nvim";source = inputs.alpha-nvim; build = false; }
        { name = "registers.nvim"; dotname = "registersDOTnvim";source = inputs.registersDOTnvim; build = false; }
        { name = "Comment.nvim"; dotname = "CommentDOTnvim";source = inputs.CommentDOTnvim; build = false; }
        { name = "trouble.nvim"; dotname = "troubleDOTnvim";source = inputs.troubleDOTnvim; build = false; }
        { name = "hop.nvim"; dotname = "hopDOTnvim";source = inputs.hopDOTnvim; build = false; }
        { name = "flash.nvim"; dotname = "flashDOTnvim";source = inputs.flashDOTnvim; build = false; }
        { name = "which-key.nvim"; dotname = "which-keyDOTnvim";source = inputs.which-keyDOTnvim; build = false; }
        { name = "satellite.nvim"; dotname = "satelliteDOTnvim";source = inputs.satelliteDOTnvim; build = false; }
        { name = "todo-comments.nvim"; dotname = "todo-commentsDOTnvim";source = inputs.todo-commentsDOTnvim; build = false; }
        { name = "nvim-notify"; dotname = "nvim-notify";source = inputs.nvim-notify; build = false; }
        { name = "lsp_lines.nvim"; dotname = "lsp_linesDOTnvim";source = inputs.lsp_linesDOTnvim; build = false; }
        { name = "nvim-osc52"; dotname = "nvim-osc52";source = inputs.nvim-osc52; build = false; }
        { name = "copilot.vim"; dotname = "copilotDOTvim";source = inputs.copilotDOTvim; build = false; }
        { name = "firenvim"; dotname = "firenvim";source = inputs.firenvim; build = true; }
        { name = "nvim-dap-python"; dotname = "nvim-dap-python";source = inputs.nvim-dap-python; build = false; }
        { name = "venv-selector.nvim"; dotname = "venv-selectorDOTnvim";source = inputs.venv-selectorDOTnvim; build = false; }
        { name = "vim-matchup"; dotname = "vim-matchup";source = inputs.vim-matchup; build = false; }
        { name = "vim-sleuth"; dotname = "vim-sleuth";source = inputs.vim-sleuth; build = false; }
        { name = "pantran.nvim"; dotname = "pantranDOTnvim";source = inputs.pantranDOTnvim; build = false; }
        { name = "rainbow"; dotname = "rainbow";source = inputs.rainbow; build = false; }
        { name = "markdown-preview.nvim"; dotname = "markdown-previewDOTnvim";source = inputs.markdown-previewDOTnvim; build = true; }
        { name = "vim-textobj-user"; dotname = "vim-textobj-user";source = inputs.vim-textobj-user; build = false; }
        { name = "vim-textobj-entire"; dotname = "vim-textobj-entire";source = inputs.vim-textobj-entire; build = false; }
        { name = "vim-interestingwords"; dotname = "vim-interestingwords";source = inputs.vim-interestingwords; build = false; }
        { name = "vim-skeletons"; dotname = "vim-skeletons";source = inputs.vim-skeletons; build = false; }
        { name = "vim-snippets"; dotname = "vim-snippets";source = inputs.vim-snippets; build = false; }
        { name = "suda.vim"; dotname = "sudaDOTvim";source = inputs.sudaDOTvim; build = false; }
        { name = "undotree"; dotname = "undotree";source = inputs.undotree; build = false; }
        { name = "vim-sandwich"; dotname = "vim-sandwich";source = inputs.vim-sandwich; build = false; }
        { name = "vim-log-highlighting"; dotname = "vim-log-highlighting";source = inputs.vim-log-highlighting; build = false; }
        { name = "telescope-asynctasks.nvim"; dotname = "telescope-asynctasksDOTnvim";source = inputs.telescope-asynctasksDOTnvim; build = false; }
        { name = "asyncrun.vim"; dotname = "asyncrunDOTvim";source = inputs.asyncrunDOTvim; build = false; }
        { name = "asynctasks.vim"; dotname = "asynctasksDOTvim";source = inputs.asynctasksDOTvim; build = false; }
        { name = "vCoolor.vim"; dotname = "vCoolorDOTvim";source = inputs.vCoolorDOTvim; build = false; }
        { name = "vim-fugitive"; dotname = "vim-fugitive";source = inputs.vim-fugitive; build = false; }
        { name = "vim-flog"; dotname = "vim-flog";source = inputs.vim-flog; build = false; }
        { name = "vim-visual-multi"; dotname = "vim-visual-multi";source = inputs.vim-visual-multi; build = false; }
        { name = "cscope_maps.nvim"; dotname = "cscope_mapsDOTnvim";source = inputs.cscope_mapsDOTnvim; build = false; }
        { name = "vim-gutentags"; dotname = "vim-gutentags";source = inputs.vim-gutentags; build = false; }
        { name = "gutentags_plus"; dotname = "gutentags_plus";source = inputs.gutentags_plus; build = false; }
        { name = "nvim-dap-ui"; dotname = "nvim-dap-ui";source = inputs.nvim-dap-ui; build = false; }
        { name = "nvim-dap-virtual-text"; dotname = "nvim-dap-virtual-text";source = inputs.nvim-dap-virtual-text; build = false; }
        { name = "nvim-dap"; dotname = "nvim-dap";source = inputs.nvim-dap; build = false; }
      ];
    } //
    import ./flake_out.nix {
      inherit self inputs;
    };
}