# Generated by dump_input.py, do not edit
{
  description = "Neovim with plugins";
  inputs = {
    neovim = {
      url = "github:neovim/neovim";
      flake = false;
    };

    lazyDOTnvim = {
      url = "github:folke/lazy.nvim";
      flake = false;
    };
    plenaryDOTnvim = {
      url = "github:nvim-lua/plenary.nvim";
      flake = false;
    };
    telescope-fzf-nativeDOTnvim = {
      url = "github:nvim-telescope/telescope-fzf-native.nvim";
      flake = false;
    };
    telescope-vim-bookmarksDOTnvim = {
      url = "github:tom-anders/telescope-vim-bookmarks.nvim";
      flake = false;
    };
    telescopeDOTnvim = {
      url = "github:nvim-telescope/telescope.nvim";
      flake = false;
    };
    sigsegvim = {
      url = "github:seandewar/sigsegvim";
      flake = false;
    };
    cellular-automatonDOTnvim = {
      url = "github:Eandrju/cellular-automaton.nvim";
      flake = false;
    };
    telescope-live-grep-argsDOTnvim = {
      url = "github:nvim-telescope/telescope-live-grep-args.nvim";
      flake = false;
    };
    nvim-bqf = {
      url = "github:kevinhwang91/nvim-bqf";
      flake = false;
    };
    nvim-hlslens = {
      url = "github:kevinhwang91/nvim-hlslens";
      flake = false;
    };
    masonDOTnvim = {
      url = "github:williamboman/mason.nvim";
      flake = false;
    };
    nvim-jdtls = {
      url = "github:mfussenegger/nvim-jdtls";
      flake = false;
    };
    rust-toolsDOTnvim = {
      url = "github:simrat39/rust-tools.nvim";
      flake = false;
    };
    clangd_extensionsDOTnvim = {
      url = "github:p00f/clangd_extensions.nvim";
      flake = false;
    };
    nvim-lspconfig = {
      url = "github:neovim/nvim-lspconfig";
      flake = false;
    };
    statuscolDOTnvim = {
      url = "github:luukvbaal/statuscol.nvim";
      flake = false;
    };
    nvim-lightbulb = {
      url = "github:kosayoda/nvim-lightbulb";
      flake = false;
    };
    fidgetDOTnvim = {
      url = "github:j-hui/fidget.nvim?ref=legacy";
      flake = false;
    };
    nvim-web-devicons = {
      url = "github:kyazdani42/nvim-web-devicons";
      flake = false;
    };
    nvim-autopairs = {
      url = "github:windwp/nvim-autopairs";
      flake = false;
    };
    auto-saveDOTnvim = {
      url = "github:Pocco81/auto-save.nvim";
      flake = false;
    };
    none-lsDOTnvim = {
      url = "github:nvimtools/none-ls.nvim";
      flake = false;
    };
    ultisnips = {
      url = "github:SirVer/ultisnips";
      flake = false;
    };
    cmp-nvim-ultisnips = {
      url = "github:quangnguyen30192/cmp-nvim-ultisnips";
      flake = false;
    };
    vim-vsnip = {
      url = "github:hrsh7th/vim-vsnip";
      flake = false;
    };
    cmp-nvim-lsp = {
      url = "github:hrsh7th/cmp-nvim-lsp";
      flake = false;
    };
    cmp-nvim-lua = {
      url = "github:hrsh7th/cmp-nvim-lua";
      flake = false;
    };
    cmp-path = {
      url = "github:hrsh7th/cmp-path";
      flake = false;
    };
    cmp-buffer = {
      url = "github:hrsh7th/cmp-buffer";
      flake = false;
    };
    cmp-omni = {
      url = "github:hrsh7th/cmp-omni";
      flake = false;
    };
    cmp-nvim-lsp-signature-help = {
      url = "github:hrsh7th/cmp-nvim-lsp-signature-help";
      flake = false;
    };
    cmp-dictionary = {
      url = "github:uga-rosa/cmp-dictionary";
      flake = false;
    };
    cmp-dap = {
      url = "github:rcarriga/cmp-dap";
      flake = false;
    };
    cmp-cmdline = {
      url = "github:hrsh7th/cmp-cmdline";
      flake = false;
    };
    lsp_signatureDOTnvim = {
      url = "github:ray-x/lsp_signature.nvim";
      flake = false;
    };
    nvim-cmp = {
      url = "github:hrsh7th/nvim-cmp";
      flake = false;
    };
    promise-async = {
      url = "github:kevinhwang91/promise-async";
      flake = false;
    };
    nvim-fundo = {
      url = "github:kevinhwang91/nvim-fundo";
      flake = false;
    };
    nvim-ufo = {
      url = "github:kevinhwang91/nvim-ufo";
      flake = false;
    };
    toggletermDOTnvim = {
      url = "github:akinsho/toggleterm.nvim";
      flake = false;
    };
    nvim-treesitter = {
      url = "github:nvim-treesitter/nvim-treesitter";
      flake = false;
    };
    playground = {
      url = "github:nvim-treesitter/playground";
      flake = false;
    };
    nvim-treesitter-textobjects = {
      url = "github:nvim-treesitter/nvim-treesitter-textobjects";
      flake = false;
    };
    indent-blanklineDOTnvim = {
      url = "github:lukas-reineke/indent-blankline.nvim";
      flake = false;
    };
    rainbow-delimitersDOTnvim = {
      url = "github:HiPhish/rainbow-delimiters.nvim";
      flake = false;
    };
    nvim-ts-autotag = {
      url = "github:windwp/nvim-ts-autotag";
      flake = false;
    };
    nvim-treesitter-context = {
      url = "github:nvim-treesitter/nvim-treesitter-context";
      flake = false;
    };
    hlargsDOTnvim = {
      url = "github:m-demare/hlargs.nvim";
      flake = false;
    };
    projectDOTnvim = {
      url = "github:ahmedkhalf/project.nvim";
      flake = false;
    };
    aerialDOTnvim = {
      url = "github:stevearc/aerial.nvim";
      flake = false;
    };
    dropbarDOTnvim = {
      url = "github:Bekaboo/dropbar.nvim";
      flake = false;
    };
    gitsignsDOTnvim = {
      url = "github:lewis6991/gitsigns.nvim";
      flake = false;
    };
    git-conflictDOTnvim = {
      url = "github:akinsho/git-conflict.nvim";
      flake = false;
    };
    diffviewDOTnvim = {
      url = "github:sindrets/diffview.nvim";
      flake = false;
    };
    nvim-colorizerDOTlua = {
      url = "github:NvChad/nvim-colorizer.lua";
      flake = false;
    };
    bufferlineDOTnvim = {
      url = "github:akinsho/bufferline.nvim";
      flake = false;
    };
    alignDOTnvim = {
      url = "github:Vonr/align.nvim";
      flake = false;
    };
    dialDOTnvim = {
      url = "github:monaqa/dial.nvim";
      flake = false;
    };
    dressingDOTnvim = {
      url = "github:stevearc/dressing.nvim";
      flake = false;
    };
    inc-renameDOTnvim = {
      url = "github:smjonas/inc-rename.nvim";
      flake = false;
    };
    lualineDOTnvim = {
      url = "github:nvim-lualine/lualine.nvim";
      flake = false;
    };
    rnvimr = {
      url = "github:kevinhwang91/rnvimr";
      flake = false;
    };
    vim-illuminate = {
      url = "github:RRethy/vim-illuminate";
      flake = false;
    };
    nvim-treeDOTlua = {
      url = "github:kyazdani42/nvim-tree.lua";
      flake = false;
    };
    bufdeleteDOTnvim = {
      url = "github:famiu/bufdelete.nvim";
      flake = false;
    };
    vim-bookmarks = {
      url = "github:MattesGroeger/vim-bookmarks";
      flake = false;
    };
    auto-session = {
      url = "github:rmagatti/auto-session";
      flake = false;
    };
    alpha-nvim = {
      url = "github:goolord/alpha-nvim";
      flake = false;
    };
    registersDOTnvim = {
      url = "github:tversteeg/registers.nvim";
      flake = false;
    };
    CommentDOTnvim = {
      url = "github:numToStr/Comment.nvim";
      flake = false;
    };
    troubleDOTnvim = {
      url = "github:folke/trouble.nvim";
      flake = false;
    };
    hopDOTnvim = {
      url = "github:smoka7/hop.nvim";
      flake = false;
    };
    flashDOTnvim = {
      url = "github:folke/flash.nvim";
      flake = false;
    };
    which-keyDOTnvim = {
      url = "github:folke/which-key.nvim";
      flake = false;
    };
    satelliteDOTnvim = {
      url = "github:lewis6991/satellite.nvim";
      flake = false;
    };
    todo-commentsDOTnvim = {
      url = "github:folke/todo-comments.nvim";
      flake = false;
    };
    nvim-notify = {
      url = "github:rcarriga/nvim-notify";
      flake = false;
    };
    lsp_linesDOTnvim = {
      url = "git+https://git.sr.ht/~whynothugo/lsp_lines.nvim";
      flake = false;
    };
    nvim-osc52 = {
      url = "github:ojroques/nvim-osc52";
      flake = false;
    };
    copilotDOTvim = {
      url = "github:github/copilot.vim";
      flake = false;
    };
    firenvim = {
      url = "github:glacambre/firenvim";
      flake = false;
    };
    nvim-dap-python = {
      url = "github:mfussenegger/nvim-dap-python";
      flake = false;
    };
    venv-selectorDOTnvim = {
      url = "github:linux-cultist/venv-selector.nvim";
      flake = false;
    };
    vim-matchup = {
      url = "github:andymass/vim-matchup";
      flake = false;
    };
    vim-sleuth = {
      url = "github:tpope/vim-sleuth";
      flake = false;
    };
    vim-easy-align = {
      url = "github:junegunn/vim-easy-align";
      flake = false;
    };
    pantranDOTnvim = {
      url = "github:potamides/pantran.nvim";
      flake = false;
    };
    rainbow = {
      url = "github:luochen1990/rainbow";
      flake = false;
    };
    markdown-previewDOTnvim = {
      url = "github:iamcco/markdown-preview.nvim";
      flake = false;
    };
    vim-textobj-entire = {
      url = "github:kana/vim-textobj-entire";
      flake = false;
    };
    vim-interestingwords = {
      url = "github:lfv89/vim-interestingwords";
      flake = false;
    };
    vim-skeletons = {
      url = "github:qsdrqs/vim-skeletons";
      flake = false;
    };
    vim-snippets = {
      url = "github:honza/vim-snippets";
      flake = false;
    };
    sudaDOTvim = {
      url = "github:lambdalisue/suda.vim";
      flake = false;
    };
    undotree = {
      url = "github:mbbill/undotree";
      flake = false;
    };
    vim-sandwich = {
      url = "github:machakann/vim-sandwich";
      flake = false;
    };
    vim-log-highlighting = {
      url = "github:MTDL9/vim-log-highlighting";
      flake = false;
    };
    telescope-asynctasksDOTnvim = {
      url = "github:GustavoKatel/telescope-asynctasks.nvim";
      flake = false;
    };
    asyncrunDOTvim = {
      url = "github:skywind3000/asyncrun.vim";
      flake = false;
    };
    asynctasksDOTvim = {
      url = "github:skywind3000/asynctasks.vim";
      flake = false;
    };
    vCoolorDOTvim = {
      url = "github:KabbAmine/vCoolor.vim";
      flake = false;
    };
    vim-fugitive = {
      url = "github:tpope/vim-fugitive";
      flake = false;
    };
    vim-flog = {
      url = "github:rbong/vim-flog";
      flake = false;
    };
    vim-visual-multi = {
      url = "github:mg979/vim-visual-multi";
      flake = false;
    };
    cscope_mapsDOTnvim = {
      url = "github:dhananjaylatkar/cscope_maps.nvim";
      flake = false;
    };
    vim-gutentags = {
      url = "github:skywind3000/vim-gutentags";
      flake = false;
    };
    gutentags_plus = {
      url = "github:skywind3000/gutentags_plus";
      flake = false;
    };
    nvim-dap-ui = {
      url = "github:rcarriga/nvim-dap-ui";
      flake = false;
    };
    nvim-dap-virtual-text = {
      url = "github:theHamsta/nvim-dap-virtual-text";
      flake = false;
    };
    nvim-dap = {
      url = "github:mfussenegger/nvim-dap";
      flake = false;
    };
  };
  outputs = { self, ... }@inputs:
    {
      plugins_list = [
        { name = "lazy.nvim"; source = inputs.lazyDOTnvim; recursive = false; }
        { name = "plenary.nvim"; source = inputs.plenaryDOTnvim; recursive = false; }
        { name = "telescope-fzf-native.nvim"; source = inputs.telescope-fzf-nativeDOTnvim; recursive = true; }
        { name = "telescope-vim-bookmarks.nvim"; source = inputs.telescope-vim-bookmarksDOTnvim; recursive = false; }
        { name = "telescope.nvim"; source = inputs.telescopeDOTnvim; recursive = false; }
        { name = "sigsegvim"; source = inputs.sigsegvim; recursive = false; }
        { name = "cellular-automaton.nvim"; source = inputs.cellular-automatonDOTnvim; recursive = false; }
        { name = "telescope-live-grep-args.nvim"; source = inputs.telescope-live-grep-argsDOTnvim; recursive = false; }
        { name = "nvim-bqf"; source = inputs.nvim-bqf; recursive = false; }
        { name = "nvim-hlslens"; source = inputs.nvim-hlslens; recursive = false; }
        { name = "mason.nvim"; source = inputs.masonDOTnvim; recursive = false; }
        { name = "nvim-jdtls"; source = inputs.nvim-jdtls; recursive = false; }
        { name = "rust-tools.nvim"; source = inputs.rust-toolsDOTnvim; recursive = false; }
        { name = "clangd_extensions.nvim"; source = inputs.clangd_extensionsDOTnvim; recursive = false; }
        { name = "nvim-lspconfig"; source = inputs.nvim-lspconfig; recursive = false; }
        { name = "statuscol.nvim"; source = inputs.statuscolDOTnvim; recursive = false; }
        { name = "nvim-lightbulb"; source = inputs.nvim-lightbulb; recursive = false; }
        { name = "fidget.nvim"; source = inputs.fidgetDOTnvim; recursive = false; }
        { name = "nvim-web-devicons"; source = inputs.nvim-web-devicons; recursive = false; }
        { name = "nvim-autopairs"; source = inputs.nvim-autopairs; recursive = false; }
        { name = "auto-save.nvim"; source = inputs.auto-saveDOTnvim; recursive = false; }
        { name = "none-ls.nvim"; source = inputs.none-lsDOTnvim; recursive = false; }
        { name = "ultisnips"; source = inputs.ultisnips; recursive = false; }
        { name = "cmp-nvim-ultisnips"; source = inputs.cmp-nvim-ultisnips; recursive = false; }
        { name = "vim-vsnip"; source = inputs.vim-vsnip; recursive = false; }
        { name = "cmp-nvim-lsp"; source = inputs.cmp-nvim-lsp; recursive = false; }
        { name = "cmp-nvim-lua"; source = inputs.cmp-nvim-lua; recursive = false; }
        { name = "cmp-path"; source = inputs.cmp-path; recursive = false; }
        { name = "cmp-buffer"; source = inputs.cmp-buffer; recursive = false; }
        { name = "cmp-omni"; source = inputs.cmp-omni; recursive = false; }
        { name = "cmp-nvim-lsp-signature-help"; source = inputs.cmp-nvim-lsp-signature-help; recursive = false; }
        { name = "cmp-dictionary"; source = inputs.cmp-dictionary; recursive = false; }
        { name = "cmp-dap"; source = inputs.cmp-dap; recursive = false; }
        { name = "cmp-cmdline"; source = inputs.cmp-cmdline; recursive = false; }
        { name = "lsp_signature.nvim"; source = inputs.lsp_signatureDOTnvim; recursive = false; }
        { name = "nvim-cmp"; source = inputs.nvim-cmp; recursive = false; }
        { name = "promise-async"; source = inputs.promise-async; recursive = false; }
        { name = "nvim-fundo"; source = inputs.nvim-fundo; recursive = true; }
        { name = "nvim-ufo"; source = inputs.nvim-ufo; recursive = false; }
        { name = "toggleterm.nvim"; source = inputs.toggletermDOTnvim; recursive = false; }
        { name = "nvim-treesitter"; source = inputs.nvim-treesitter; recursive = true; }
        { name = "playground"; source = inputs.playground; recursive = false; }
        { name = "nvim-treesitter-textobjects"; source = inputs.nvim-treesitter-textobjects; recursive = false; }
        { name = "indent-blankline.nvim"; source = inputs.indent-blanklineDOTnvim; recursive = false; }
        { name = "rainbow-delimiters.nvim"; source = inputs.rainbow-delimitersDOTnvim; recursive = false; }
        { name = "nvim-ts-autotag"; source = inputs.nvim-ts-autotag; recursive = false; }
        { name = "nvim-treesitter-context"; source = inputs.nvim-treesitter-context; recursive = false; }
        { name = "hlargs.nvim"; source = inputs.hlargsDOTnvim; recursive = false; }
        { name = "project.nvim"; source = inputs.projectDOTnvim; recursive = false; }
        { name = "aerial.nvim"; source = inputs.aerialDOTnvim; recursive = false; }
        { name = "dropbar.nvim"; source = inputs.dropbarDOTnvim; recursive = false; }
        { name = "gitsigns.nvim"; source = inputs.gitsignsDOTnvim; recursive = false; }
        { name = "git-conflict.nvim"; source = inputs.git-conflictDOTnvim; recursive = false; }
        { name = "diffview.nvim"; source = inputs.diffviewDOTnvim; recursive = false; }
        { name = "nvim-colorizer.lua"; source = inputs.nvim-colorizerDOTlua; recursive = false; }
        { name = "bufferline.nvim"; source = inputs.bufferlineDOTnvim; recursive = false; }
        { name = "align.nvim"; source = inputs.alignDOTnvim; recursive = false; }
        { name = "dial.nvim"; source = inputs.dialDOTnvim; recursive = false; }
        { name = "dressing.nvim"; source = inputs.dressingDOTnvim; recursive = false; }
        { name = "inc-rename.nvim"; source = inputs.inc-renameDOTnvim; recursive = false; }
        { name = "lualine.nvim"; source = inputs.lualineDOTnvim; recursive = false; }
        { name = "rnvimr"; source = inputs.rnvimr; recursive = false; }
        { name = "vim-illuminate"; source = inputs.vim-illuminate; recursive = false; }
        { name = "nvim-tree.lua"; source = inputs.nvim-treeDOTlua; recursive = false; }
        { name = "bufdelete.nvim"; source = inputs.bufdeleteDOTnvim; recursive = false; }
        { name = "vim-bookmarks"; source = inputs.vim-bookmarks; recursive = false; }
        { name = "auto-session"; source = inputs.auto-session; recursive = false; }
        { name = "alpha-nvim"; source = inputs.alpha-nvim; recursive = false; }
        { name = "registers.nvim"; source = inputs.registersDOTnvim; recursive = false; }
        { name = "Comment.nvim"; source = inputs.CommentDOTnvim; recursive = false; }
        { name = "trouble.nvim"; source = inputs.troubleDOTnvim; recursive = false; }
        { name = "hop.nvim"; source = inputs.hopDOTnvim; recursive = false; }
        { name = "flash.nvim"; source = inputs.flashDOTnvim; recursive = false; }
        { name = "which-key.nvim"; source = inputs.which-keyDOTnvim; recursive = false; }
        { name = "satellite.nvim"; source = inputs.satelliteDOTnvim; recursive = false; }
        { name = "todo-comments.nvim"; source = inputs.todo-commentsDOTnvim; recursive = false; }
        { name = "nvim-notify"; source = inputs.nvim-notify; recursive = false; }
        { name = "lsp_lines.nvim"; source = inputs.lsp_linesDOTnvim; recursive = false; }
        { name = "nvim-osc52"; source = inputs.nvim-osc52; recursive = false; }
        { name = "copilot.vim"; source = inputs.copilotDOTvim; recursive = false; }
        { name = "firenvim"; source = inputs.firenvim; recursive = true; }
        { name = "nvim-dap-python"; source = inputs.nvim-dap-python; recursive = false; }
        { name = "venv-selector.nvim"; source = inputs.venv-selectorDOTnvim; recursive = false; }
        { name = "vim-matchup"; source = inputs.vim-matchup; recursive = false; }
        { name = "vim-sleuth"; source = inputs.vim-sleuth; recursive = false; }
        { name = "vim-easy-align"; source = inputs.vim-easy-align; recursive = false; }
        { name = "pantran.nvim"; source = inputs.pantranDOTnvim; recursive = false; }
        { name = "rainbow"; source = inputs.rainbow; recursive = false; }
        { name = "markdown-preview.nvim"; source = inputs.markdown-previewDOTnvim; recursive = true; }
        { name = "vim-textobj-entire"; source = inputs.vim-textobj-entire; recursive = false; }
        { name = "vim-interestingwords"; source = inputs.vim-interestingwords; recursive = false; }
        { name = "vim-skeletons"; source = inputs.vim-skeletons; recursive = false; }
        { name = "vim-snippets"; source = inputs.vim-snippets; recursive = false; }
        { name = "suda.vim"; source = inputs.sudaDOTvim; recursive = false; }
        { name = "undotree"; source = inputs.undotree; recursive = false; }
        { name = "vim-sandwich"; source = inputs.vim-sandwich; recursive = false; }
        { name = "vim-log-highlighting"; source = inputs.vim-log-highlighting; recursive = false; }
        { name = "telescope-asynctasks.nvim"; source = inputs.telescope-asynctasksDOTnvim; recursive = false; }
        { name = "asyncrun.vim"; source = inputs.asyncrunDOTvim; recursive = false; }
        { name = "asynctasks.vim"; source = inputs.asynctasksDOTvim; recursive = false; }
        { name = "vCoolor.vim"; source = inputs.vCoolorDOTvim; recursive = false; }
        { name = "vim-fugitive"; source = inputs.vim-fugitive; recursive = false; }
        { name = "vim-flog"; source = inputs.vim-flog; recursive = false; }
        { name = "vim-visual-multi"; source = inputs.vim-visual-multi; recursive = false; }
        { name = "cscope_maps.nvim"; source = inputs.cscope_mapsDOTnvim; recursive = false; }
        { name = "vim-gutentags"; source = inputs.vim-gutentags; recursive = false; }
        { name = "gutentags_plus"; source = inputs.gutentags_plus; recursive = false; }
        { name = "nvim-dap-ui"; source = inputs.nvim-dap-ui; recursive = false; }
        { name = "nvim-dap-virtual-text"; source = inputs.nvim-dap-virtual-text; recursive = false; }
        { name = "nvim-dap"; source = inputs.nvim-dap; recursive = false; }
      ];
    } //
    import ./flake_out.nix {
      inherit self inputs;
    };
}