format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status"""

[directory]
truncation_length = 0
truncate_to_repo = false

[git_status]
modified = '!${count}'
untracked = '?${count}'
staged = '+${count}'
deleted = '✘${count}'
