#:schema https://yazi-rs.github.io/schemas/keymap.json

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "<Right>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "z"
run  = "plugin smart-goto 'jump zoxide'"
desc = "Jump to a directory using zoxide"

[[mgr.prepend_keymap]]
on   = "Z"
run  = "plugin smart-goto 'jump fzf'"
desc = "Jump to a directory, or reveal a file using fzf"

[[mgr.prepend_keymap]]
on   = [ "g", "h" ]
run  = "plugin smart-goto 'jump ~'"
desc = "Go to the home directory"

[[mgr.prepend_keymap]]
on   = [ "g", "H" ]
run  = "plugin smart-goto 'jump /mnt/Users/qsdrqs'"
desc = "Go to the Windows home directory"

[[mgr.prepend_keymap]]
on   = [ "g", "w" ]
run  = "plugin smart-goto 'jump /home/qsdrqs/Documents/WeChat\\ Files/wxid_ap6bpq3h92zg22/FileStorage/File'"
desc = "Go to the WeChat directory"

[[mgr.prepend_keymap]]
on   = [ "g", "q" ]
run  = "plugin smart-goto 'jump /home/qsdrqs/Documents/Tencent\\ Files/1143661020/FileRecv'"
desc = "Go to the QQ directory"

[[mgr.prepend_keymap]]
on   = [ "g", "c" ]
run  = "plugin smart-goto 'jump ~/.config'"
desc = "Go to the config directory"

[[mgr.prepend_keymap]]
on   = [ "g", "d" ]
run  = "plugin smart-goto 'jump follow ~/Downloads/'"
desc = "Follow the link, or go to the downloads directory"

[[mgr.prepend_keymap]]
on   = [ "g", "t" ]
run  = "plugin smart-goto 'jump /tmp'"
desc = "Go to the temporary directory"

[[mgr.prepend_keymap]]
on   = [ "g", "<Space>" ]
run  = "plugin smart-goto 'jump interactive'"
desc = "Go to a directory interactively"

[[mgr.prepend_keymap]]
on   = "<C-o>"
run  = "plugin smart-goto 'back'"
desc = "Jump back"

[[mgr.prepend_keymap]]
on   = "<Tab>"
run  = "plugin smart-goto 'forward'"
desc = "Jump forward"

[[mgr.prepend_keymap]]
on   = "s"
run  = "plugin searchjump"
desc = "Searchjump mode"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
on   = [ "b", "b" ]
run  = "plugin dircount"
desc = "Count directory contents"

[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin gitstatus"
desc = "Show Git status"

[[mgr.prepend_keymap]]
on   = [ "d", "d" ]
run  = [ "yank --cut", "escape --visual --select" ]
desc = "Cut the selected files"

[[mgr.prepend_keymap]]
on   = "D"
run  = [ "remove", "escape --visual --select" ]
desc = "Move the files to the trash"

[[mgr.prepend_keymap]]
on   = [ "d", "D" ]
run  = [ "remove --permanently", "escape --visual --select" ]
desc = "Permanently delete the files"

[[mgr.prepend_keymap]]
on   = [ "y", "y" ]
run  = [ "yank", "escape --visual --select" ]
desc = "Copy the selected files"

[[mgr.prepend_keymap]]
on   = [ "y", "r" ]
run  = "plugin copy-relative-path"
desc = "Copy the relative path"

[[mgr.prepend_keymap]]
on   = [ "y", "p" ]
run  = "copy path"
desc = "Copy the absolute path"

[[mgr.prepend_keymap]]
on   = [ "y", "d" ]
run  = "copy dirname"
desc = "Copy the path of the parent directory"

[[mgr.prepend_keymap]]
on   = [ "y", "f" ]
run  = "copy filename"
desc = "Copy the name of the file"

[[mgr.prepend_keymap]]
on   = [ "y", "n" ]
run  = "copy name_without_ext"
desc = "Copy the name of the file without the extension"

[[mgr.prepend_keymap]]
on   = [ "p", "p" ]
run  = "paste"
desc = "Paste the files"

[[mgr.prepend_keymap]]
on   = [ "p", "l" ]
run  = "link"
desc = "Symlink the absolute path of files"

[[mgr.prepend_keymap]]
on   = [ "p", "L" ]
run  = "link --relative"
desc = "Symlink the relative path of files"

[[mgr.prepend_keymap]]
on   = "r"
run  = "open --interactive"
desc = "Open the selected files interactively"

[[mgr.prepend_keymap]]
on   = "a"
run  = "rename --cursor=before_ext"
desc = "Rename a file or directory"

[[mgr.prepend_keymap]]
on   = "A"
run  = "rename"
desc = "Rename a file or directory"

[[mgr.prepend_keymap]]
on   = "I"
run  = "rename --cursor=start"
desc = "Rename a file or directory"

[[mgr.prepend_keymap]]
on   = "c"
run  = "create"
desc = "Create a file or directory"

[[mgr.prepend_keymap]]
on   = "V"
run  = "visual_mode"
desc = "Enter visual mode (selection mode)"

[[mgr.prepend_keymap]]
on   = "<C-h>"
run  = "hidden toggle"
desc = "Toggle the visibility of hidden files"

[[mgr.prepend_keymap]]
on   = [ "\\", "s" ]
run  = "search --via=fd"
desc = "Search files by name using fd"

[[mgr.prepend_keymap]]
on   = [ "\\", "S" ]
run  = "search --via=rg"
desc = "Search files by content using ripgrep"

[[mgr.prepend_keymap]]
on   = "S"
run  = 'shell "zsh" --block'
desc = "Open ZSH shell"

[[mgr.prepend_keymap]]
on   = "<C-g>"
run  = 'shell "lazygit" --block'
desc = "Open lazygit"

[[mgr.prepend_keymap]]
on   = "K"
run  = "arrow -5"
desc = "Move cursor up 5 lines"

[[mgr.prepend_keymap]]
on   = "J"
run  = "arrow 5"
desc = "Move cursor down 5 lines"

[[mgr.prepend_keymap]]
on   = "<S-Up>"
run  = "arrow -5"
desc = "Move cursor up 5 lines"

[[mgr.prepend_keymap]]
on   = "<S-Down>"
run  = "arrow 5"
desc = "Move cursor down 5 lines"

[[mgr.prepend_keymap]]
on   = "<PageUp>"
run  = "seek -5"
desc = "Seek up 5 units in the preview"

[[mgr.prepend_keymap]]
on   = "<PageDown>"
run  = "seek 5"
desc = "Seek down 5 units in the preview"
