#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
linemode = "size"

[opener]
edit = [
	{ run = 'editor-wrapped %s', desc = "Edit", block = true, for = "unix" },
	{ run = 'code %s', orphan = true, for = "windows" },
]
open_detach = [
	{ run = 'xdg-open %s1', desc = "Open (Detached)", for = "linux", orphan = true },
	{ run = 'xdg-open %s1', desc = "Open", for = "linux" },
	{ run = 'open %s', desc = "Open", for = "macos" },
	{ run = 'start "" %s1', orphan = true, desc = "Open", for = "windows" },
]
play = [
	{ run = 'mpv --force-window %s', orphan = true, for = "unix" },
	{ run = 'mpv --force-window %s', orphan = true, for = "windows" },
	{ run = '''mediainfo %s1; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]

[[open.prepend_rules]]
mime = "application/pdf"
use = [ "open_detach", "reveal", "edit" ]

[tasks]
file_workers     = 25
plugin_workers   = 25
fetch_workers    = 10
preload_workers  = 10
process_workers  = 25
bizarre_retry    = 5
image_alloc      = 536870912 # 512MB
image_bound      = [ 0, 0 ]
suppress_preload = true

[[plugin.prepend_fetchers]]
group = "mime"
url   = "local://*"
run   = "mime-ext.local"
prio  = "high"

[[plugin.prepend_fetchers]]
group = "mime"
url   = "remote://*"
run   = "mime-ext.remote"
prio  = "high"

[[plugin.append_fetchers]]
group = "dircount"
url   = "*/"
run   = "dircount"

[[plugin.append_fetchers]]
group = "gitstatus"
mime  = "*"
run   = "gitstatus"

[input]
cursor_blink = false

[confirm]
overwrite_body = "Will overwrite the following file:"
quit_body      = "The following task is still running, are you sure you want to quit?"

[which]
sort_by = "none"
