general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# listener {
#     timeout = 300                                # 5min.
#     on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
#     on-resume = brightnessctl -r                 # monitor backlight restore.
# }

# turn off keyboard backlight after 30s idle for asus laptops
listener {
    timeout = 30
    on-timeout = "$HOME/.config/hypr/asus-kbd-backlight-idle.sh" off
    on-resume = "$HOME/.config/hypr/asus-kbd-backlight-idle.sh" restore
}

listener {
    timeout = 600                                 # 10min, gives 2 seconds to lock the screen.
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

listener {
    timeout = 602                                 # 10min
    on-timeout = hyprctl dispatch dpms off        # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on          # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 602                                 # 10min
    on-timeout = niri msg action power-off-monitors        # screen off when timeout has passed
    on-resume = niri msg action power-on-monitors          # screen on when activity is detected after timeout has fired.
}

# listener {
#     timeout = 1800                                # 30min
#     on-timeout = systemctl suspend                # suspend pc
# }
